### ISSUE TITLE
Translation help needed

### ISSUE THREAD

**Issue by didiatworkz** [didiatworkz/screenly-ose-monitoring#54]
Hello together,

after the release of V4.0 it's possible to change the language of the whole system.

For that, I need some co-workers who can translate the system in other languages.
Are you interested? - Then write me an email at github@atworkz.de and tell me which language you can support.
I will contact you as soon it's impossible.

Thank you in advance

**Comment by JurakZdenek** [comment]
Hello, I want to commend you for a great job and a very useful project. I really appreciate it. I will be happy to help you with the translation into Czech, if it is easy. I only know the basics of PHP. Thank you again.

**Comment by c4rv88** [comment]
Hello! I can help to translate to portuguese-br. email: c4rv88@gmail.com

**Comment by omival-val** [comment]
Buenas tardes;
Mucho gusto espero estén bien ,quiero felicitarlos por tan grande proyecto ,quiero traducirlo a español 
mi correo es jorgevargas.soluciones@gmail.com

Quedo atento
