### ISSUE TITLE
upload button & file size limit issue

### ISSUE THREAD

**Issue by MangNPB** [didiatworkz/screenly-ose-monitoring#64]
Single player upload button disappear if 1 file (multiple files per attempt session) out of the list has size greater than MB allowed in setting. Button will not reappear even if the large file is removed from the list. The page must be reloaded again. Most people knows SOMO would raised the limit to start but for new comers it could be head scratching.

system = debian buster RPI4 with latest SOMO and SOMA installed.

**Comment by didiatworkz** [comment]
Hello @MangNPB
I can confirm the behavior - It will be fixed in the next update.

Regards,
didiatworkz

**Comment by MangNPB** [comment]
![image](https://user-images.githubusercontent.com/44915183/107672885-6b23c300-6c63-11eb-8100-b93b283f8462.png)
![image](https://user-images.githubusercontent.com/44915183/107672911-724ad100-6c63-11eb-83db-7b0f7dbed9d9.png)


multiupload at least show up "reload" but single upload doesn't

Mang
