### ISSUE TITLE
Youtube link

### ISSUE THREAD

**Issue by Doucheur** [didiatworkz/screenly-ose-monitoring#69]
Hello !

I already said it, but this project is very interesting and useful.

Here is my issue :
When trying to upload a Youtube video by using its link, it's trying to display the whole Youtube page instead of the Video.

## Expected Behavior

By example, I want to display and ear this video on my Screenly player :
https://www.youtube.com/watch?v=h-jxgXxRgnM

Using the web interface of my Screenly player, that's work like a charm.

![image](https://user-images.githubusercontent.com/75076394/112011421-8cac8000-8b28-11eb-8309-e946f9c7a2e9.png)

## Current Behavior

When I create an asset from SOMO, and adding the Youtube URL, here is the result

![image](https://user-images.githubusercontent.com/75076394/112011551-a8b02180-8b28-11eb-8612-68931a85c12b.png)

I'm not a dev so I can't help you resolving this :( 

Thanks ! 
Matthias

**Comment by didiatworkz** [comment]
Hello @Doucheur,

thanks for your feedback I found the problem and I will fix it.

Cheers,
didiatworkz

**Comment by Doucheur** [comment]
Hello @didiatworkz ,

Thank you very much ! 
Good luck,

Cheers,
Doucheur

**Comment by bartjackbakker** [comment]
Hi @didiatworkz 

Do you have an update about the release date of this fix?

Cheers,
Bart
