### ISSUE TITLE
Screenly-OSE Development / Master Branch Compatibility

### ISSUE THREAD

**Issue by BrendonKoz** [didiatworkz/screenly-ose-monitoring#72]
## Expected Behavior
Currently, SOMO does not detect an installation of the development branch of Screenly-OSE (which has been suggested by their own devs to be installed in order to solve certain problems - for me, that is unsupported HTML5/CSS rendering issues with the UZBL browser).

## Current Behavior
SOMO will happily install itself, and I was able to get it to run atop a pre-installed OSE Dev branch, but since it couldn't detect OSE properly that was already running on the raspberry pi (it said it was found, but...), it took control of port 80, which (in this case) it shouldn't have. OSE was then inaccessible until it was accessed via SSL, but SOMO still couldn't communicate with it as it was not found.

## Steps to Reproduce (for bugs)
1. Install Screenly-OSE as according to the SOMO Wiki.
2. During installation of Screenly-OSE, choose the development branch over the "Stable" branch
3. Once complete, install SOMO.

## Context
Screenly-OSE's development has slowed a bit, but the development branch seems to be the more appropriate version than the stable branch from my own usage/testing. That said, I know there's also a Balena branch, so I don't know how difficult it might be to support all of the various versions of Screenly-OSE (I don't know if it can detect the Balena version).

## Your Environment

* Screenly OSE Monitoring Version: Assuming v4.1 (used the curl-based bash script)
* Screenly OSE Version: Assuming the update to Spring 10.1 (used the curl-based bash script)
* Raspbian Version: Buster as downloaded via Raspberry Pi imager (Lite), after an `apt update` and `apt upgrade`.

If SOMO will only be supporting the stable, standard version of Screenly-OSE (an acceptable stance) - could the README.md of the project at least be updated? Thank you! This project is awesome. I really want to be able to use it, but appreciate those who can thanks to your work.

**Comment by didiatworkz** [comment]
Hello @BrendonKoz,

thanks for your feedback.
I figure out what the issue caused.
To fix that I need to redesign the whole installation and server process while screenly-OSE currently block the Port 80 and nginx can't be installed 😞 

Quick solution for you: Install SOMO on a device without Screenly. Otherwise, you need to wait until I implement the new installer and server process 👍🏻 

I added this to V4.2

Cheers,
didiatowrkz
