### ISSUE TITLE
Error during installation process

### ISSUE THREAD

**Issue by jcsanchezrb** [didiatworkz/screenly-ose-monitoring#73]
During the installation process, the script return an error and at the end of the process, the app isn't access.

I attach text file with the messages returned by the script.
[Install_Somo.txt](https://github.com/didiatworkz/screenly-ose-monitoring/files/6551988/Install_Somo.txt)
[Install_Somo.txt](https://github.com/didiatworkz/screenly-ose-monitoring/files/6551992/Install_Somo.txt)

## Your Environment
I get the same error with or without apt update & apt upgrade before.
* Screenly OSE Monitoring Version: Version 4.1
* Screenly OSE Version: NOne
* Raspbian Version: Raspbian GNU/Linux 10 (buster)
* Browser Name and version: Google Chrome Versión 90.0.4430.212
* Operating System and version (desktop): Windows 10 Pro version 21H1

**Comment by didiatworkz** [comment]
Hello @jcsanchezrb,

which Raspbian image do you use (lite/desktop)?
And on which PI version do you installed SOMO?

Regards,
didiatworkz

**Comment by jcsanchezrb** [comment]
I was using lite version and I was using Raspberry PI 3 Model B/B+.
