### ISSUE TITLE
v4.2 docker issues

### ISSUE THREAD

**Issue by sisensee** [didiatworkz/screenly-ose-monitoring#75]
Your issue may already be reported!
Please search on the [issue tracker](https://github.com/didiatworkz/screenly-ose-monitoring/issues) before creating one.

Let me start by saying thank you for this fantastic project! I know this is not a general release but thought it might help. Somehow. 

## Expected Behavior
Docker composes, initial page loads with "Temporarily down for maintenance"
Trying to learn to use docker, 100% possibles this is user error. 

## Current Behavior
After compose PHP and NginX online but not connecting. Logs show.  Attempted first with modified ports on Nginx, 

## Possible Solution
According to the logs its more than likely a permissions issue, however I am not good enough with docker to help beyond that at this point. Unable to open bash in docker to adjust permissions.

## Steps to Reproduce (for bugs)
Download v4.2 zip, unzip, open folder, (tried both as stock and with modified Nginx ports) docker-compose up -d. Verify in portainer containers are running. 

## Context
Trying to install SOMO in docker, will combine with Nginx proxy manager, attempting to include Authelia for MFA as well (obviously outside the scope of this). 

## Your Environment
* Screenly OSE Monitoring Version: v4.2
* Screenly OSE Version: N/A
* Raspbian Version: Buster
* Browser Name and version: Safari 14.1 & Chrome 92.0.4515.107
* Operating System and version (desktop or mobile):
* Logs: 
[_somo-nginx_logs.txt](https://github.com/didiatworkz/screenly-ose-monitoring/files/6918494/_somo-nginx_logs.txt)
[_somo-php_logs.txt](https://github.com/didiatworkz/screenly-ose-monitoring/files/6918495/_somo-php_logs.txt)

**Comment by didiatworkz** [comment]
Hello @sisensee ,

Sorry but 4.2 is not official and still in progress.

Currently, no support for this issue.
Please use the master branch.

Best
didiatworkz
