### ISSUE TITLE
4k resolution issue

### ISSUE THREAD

**Issue by snipper1993** [didiatworkz/screenly-ose-monitoring#76]
Hello, there is a problem in OSE Monitoring with players, on hdmi with 1920x1680 resolution  is ok, I can se what is running from management console but when raspberry pi is connected on hdmi with 3848x2160 resolution the image is not showing, shows that is online,  somo management and somo player are updated .

**Comment by didiatworkz** [comment]
Hello @snipper1993,

thanks for reporting that issue - For me, it isn't possible to reconstruct that issue because I don't own a 4k screen 😞 
Can you paste a screenshot from the overview, maybe?

Best
didiatworkz

**Comment by snipper1993** [comment]
Hello @didiatworkz,
I attached the screenshot from the overview in somo management.
I tried in /boot/config.txt to change following lines but if the raspbery pi is restart few times resolution is change again to 4k because the tv is 4k by default, so i change following lines to dislplay only full hd:
////////////////////////////////
disable_overscan=1
hdmi_force_hotplug=1
hdmi_group=1
hdmi_mode=31
///////////////////////////////
Best,
@snipper1993 
...............................................END

![screenly_4k_resolution](https://user-images.githubusercontent.com/45271803/144972347-96a5346a-4fec-4476-9a9a-30b2bea31163.PNG)

**Comment by didiatworkz** [comment]
Hello @snipper1993 
I was successfully to reproduce the issue... (I forgot that I own a 4K TV)
When you play HD content, everything work fine: 
![image](https://user-images.githubusercontent.com/18490798/145106870-14f94097-59d0-40e4-ad2a-c03106ca9d12.png)

But the issue happens when you play 4k content -> Then the add-on has this error message `vc_dispmanx_snapshot() failed` until HD content plays again.

I will investigate this and let you know when I find something more.

Best
didiatworkz

**Comment by didiatworkz** [comment]
Hello @snipper1993 

you need to reinstall the add-on on your devices (v3.1) or set the GPU memory to minimum 128MB `raspi-config nonint do_memory_split 128`

That solved the problem for me:
![image](https://user-images.githubusercontent.com/18490798/145110573-5baf273b-b415-48c7-b5e1-c327098870fd.png)

Please let me know if this solution also solve your issue.

Best
didiatworkz

**Comment by snipper1993** [comment]
Hello @didiatworkz 
It worked using `raspi-config nonint do_memory_split 128`,  many thanks.

**Comment by didiatworkz** [comment]
You're welcome
