### ISSUE TITLE
Use SOMO for external ip addresses + port

### ISSUE THREAD

**Issue by damienpeerbolte** [didiatworkz/screenly-ose-monitoring#77]
Hi, I know this application is only tested for local addresses. I have tried to connect to an external raspberry, and what I've seen is that I need to forward port 80 and 443 to properly use it. Now my only problem is that I can only use one raspsberry since I cannot enter ports in SOMO. Is there maybe a way to do this? Thanks in advance.

**Comment by didiatworkz** [comment]
Hello @damienpeerbolte,

I don't understand, what do you do and what do you want from me?
When you open the ports 80 and 443 you need maybe also 9020 on a player when you installed the add-on.
But in general, I would suggest not to do that and create ssh tunnels between the devices and SOMO for more security.
The system isn't designed for external accesses.

Best
didiatworkz

**Comment by ivanzeljko** [comment]
Is this application designed to work with **VPN'**s?

We use Wireguard VPN and upload and multi-upload works for pictures.
When we do multi-upload of video (cca 20MB size) we get _"Request timed out after 30000 seconds"_

Then we have to wait 4-5 minutes for clients to recover and get online.

Any suggestions for dislocated clients (players)?

![player1](https://user-images.githubusercontent.com/3628393/145393865-f39c4125-eb0d-4ae4-9f28-ebd949e85237.png)
![player2](https://user-images.githubusercontent.com/3628393/145393869-1ba9aca2-c78a-4213-a697-db4b63a284c9.png)

**Comment by didiatworkz** [comment]
Hello @ivanzeljko,

I created a new issue about your problem - This has nothing to do with this issue here. New Issue -> #86

**Comment by didiatworkz** [comment]
Hello @damienpeerbolte,

after no feedback, I will close this ticket.

Best
didiatworkz
