### ISSUE TITLE
RPI 4 support ?

### ISSUE THREAD

**Issue by Tom2446** [didiatworkz/screenly-ose-monitoring#80]
Hello,

Does screenly-ose-monitoring work on raspi 4B ?
I was able to install it without errors but I cannot access the UI.

**Comment by didiatworkz** [comment]
Hello @Tom2446,

yes it is - when do you installed somo? - I ask this because the repo is updated some hours ago.

Best
didiatworkz

**Comment by didiatworkz** [comment]
Hello @Tom2446,

there is an issue in the latest docker container - I'm on it

**Comment by didiatworkz** [comment]
Hello @Tom2446 ,

please remove the old image: `sudo systemctl stop docker.somo && sudo docker stop somo && sudo docker rm somo` and restart the device.
I will close this issue here - If anything else, let me know.

Best
didiatworkz
