### ISSUE TITLE
Is this application designed to work with **VPN**s?

### ISSUE THREAD

**Issue by didiatworkz** [didiatworkz/screenly-ose-monitoring#86]
Is this application designed to work with **VPN**s?

We use Wireguard VPN and upload and multi-upload works for pictures.
When we do multi-upload of video (cca 20MB size) we get _"Request timed out after 30000 seconds"_

Then we have to wait 4-5 minutes for clients to recover and get online.

Any suggestions for dislocated clients (players)?

![player1](https://user-images.githubusercontent.com/3628393/145393865-f39c4125-eb0d-4ae4-9f28-ebd949e85237.png)
![player2](https://user-images.githubusercontent.com/3628393/145393869-1ba9aca2-c78a-4213-a697-db4b63a284c9.png)

_Originally posted by @ivanzeljko in https://github.com/didiatworkz/screenly-ose-monitoring/issues/77#issuecomment-989794261_

**Comment by didiatworkz** [comment]
Hello @ivanzeljko,

can you record the network traffic via DevTools from your browser (Press F12 and navigate to "Network")
![image](https://user-images.githubusercontent.com/18490798/145441381-60977803-0de6-493c-8e84-06fb6bc8d6e4.png)

Clear all entries in the list and start uploading. 
After that, you can export the protocol as HAR and attach it in this issue, please.

Best
didiatworkz

**Comment by ivanzeljko** [comment]
Hello,

We have tested uploads with Multi Uploader.
Smaller files are uploading, but bigger files are not completed successfully.
More details in HAR files.

[HAR files](https://easyupload.io/ni506d)

SOMO:
![image](https://user-images.githubusercontent.com/3628393/146543742-39ecc4ce-b746-4c9c-af86-cc1dc6fc8aaa.png)

Screenly OSE Player RPi3:
![image](https://user-images.githubusercontent.com/3628393/146543557-76a3928a-5c22-42e2-b75e-d8301e7480b2.png)


Thank you for your help

**Comment by didiatworkz** [comment]
Hello @ivanzeljko 
normally I would stop support here because SOMO is installed on a non-supported system.

But the problem here is that POST requests are not sent chunked to the server.
![image](https://user-images.githubusercontent.com/18490798/146653844-5799352c-088e-47c0-807d-11a4c44eb483.png)

What is the reason for this and how to fix it, I can't say for a CentOS.
My recommendation here would be to install SOMO on a Debian system.
I just set up a complete OSE and SOMO system to check this again -> With to recommend hardware, everything works :
![image](https://user-images.githubusercontent.com/18490798/146653867-65073bc5-2fb2-488f-829b-6aac3aaa39e8.png)

**Comment by ivanzeljko** [comment]
Thank you. Sorry I didn't checked Requirements section.

Will try it on Debian OS.

**Comment by ivanzeljko** [comment]
Hello,

Just a follow-up on this, although its not supported.

I have tried installing latest SOMO v4.3 (Docker version) to Debian 10 (Buster) on x64 PC.
Multi-Upload does not work, chunk with index zero can't start - just like in old HAR files from CentOS . 

**Upload to individual players works really OK with 3MB chunks** (SOMO Menu: Players -> Some player -> New asset).
This also works on CentOS too.

I'm a little confused, shouldn't the docker version work the same no matter which OS or architecture runs it.

Thanks.

**Comment by didiatworkz** [comment]
Hello @ivanzeljko,

You're totally right - I forgot that is everything into a container... Sorry for that.
Yes, 3 MB files are in general no problem regarding the packages will split to 3 MB packages.
Are the players who are to receive the content all on the same network?
Otherwise, I cannot explain it, as my test system does not show this error in this way.
The only thing I have noticed in the last few days, but cannot yet verify 100%, is that Screenly OSE Master has a problem with the file upload api - but I don't currently have the time to test the problem in detail. - Your device works with production, which is also used in my test system...

Can you tell me a little bit more about your infrastructure?
Did you connect the devices via VPN Tunnels?

Best
didiatworkz

**Comment by ivanzeljko** [comment]
Hello @didiatworkz ,

Thank you for your info. Upload of bigger video files (18MB chunked into 6 pieces) is working really good when uploding to individual Player (via SOMO menu: Players -> New asset). But Multi-Upload of same file gets stuck at start of first chunk (index 0).

Infrastructure is consisting of one virtual cloud server (CentOS 7) with SOMO on it. Players are on RaspberryPi3B's. Players are in different phisical locations, connected to SOMO via lightweight Wireguard VPN.

I will do more tests with different combinations, and let you know results.

Thanks

**Comment by didiatworkz** [comment]
Hello @ivanzeljko,
Is there anything new here?

Best
didiaworkz

**Comment by ivanzeljko** [comment]
Hello @didiatworkz,

I will try to get some time to go trough more detailed tests.

Thanks.
