### ISSUE TITLE
Synchronize  display of assets on multiple players

### ISSUE THREAD

**Issue by ivanzeljko** [didiatworkz/screenly-ose-monitoring#89]
**Is your feature request related to a problem? Please describe.**
We would like to see videos synced on multiple players.

**Describe the solution you'd like**
Synchronize  display of assets on multiple players
Maybe use Ansible or some of these tools https://www.tecmint.com/run-commands-on-multiple-linux-servers/

**Describe alternatives you've considered**
We have tried enabling NTP and adding identical assets  on multiple players, but it's not OK.

**Comment by didiatworkz** [comment]
Hello @ivanzeljko,
I have looked at your suggestion and I am sorry to tell you that your idea is unfortunately not possible due to limitations of screenly OSE.
Unfortunately, I cannot implement it.

**Comment by ivanzeljko** [comment]
Hello @didiatworkz ,

Thank you for your work.
