### ISSUE TITLE
Database copy from 4.1 to later versions

### ISSUE THREAD

**Issue by d0cdave** [didiatworkz/screenly-ose-monitoring#90]
What's your question?

Hi! Is there a script to change the 4.1 database to 4.3? When I attempt to copy the database.db file between versions the screen list is blank but everything else seems ok. 

Background - Running ScreenlyManager in an i386 Raspbian Desktop VM. When upgrading to 4.3, docker will not install (repo issue with i386 Raspbian). Built a Debian 11x64 VM and its working great. We just need to get the existing DB from the old OS to the new docker container without breaking. 

Thanks!
-David

**Comment by didiatworkz** [comment]
Hello @d0cdave 

unfortunately, the docker container isn't build for i386.
But yes, you can trigger the database update when you create a text file named: `version_old.txt` and write `4.1` into it and put this file in the shared folder where the database file located.
Then the script will update the database.

Best
didiatworkz

Best

**Comment by d0cdave** [comment]
This worked great. Added the file with the version number in the same folder as the database in the docker container, ran the upgrade curl script again and it worked great! Thanks for the quick reply. 

Server runs much better in a Deb 64bit VM with over 100 screens.
