### ISSUE TITLE
Blank page after upgrade 

### ISSUE THREAD

**Issue by GhoperFX** [didiatworkz/screenly-ose-monitoring#91]
Hello

For some time SOMO had stopped working for me and it was due to some system update.

Now I have tried to update to the latest version and the behavior is the same, when I log in it only shows me a blank screen.

Any idea what could be happening?

Thanks.

**Comment by GhoperFX** [comment]
I am reviewing the extent of my knowledge, which is limited in programming ;-)

After the login the page loads all its source but it shows blank in the browser, it's something very strange.

I wish I could help with something else :-(

**Comment by didiatworkz** [comment]
Hello @GhoperFX ,

That's don't sounds good..
Of you use a Raspberry Pi then you need to run this command:

`echo 4.1 > /home/pi/.somo/version_old.txt`

After that you need to reload the page and normally the maintenance mode will be activated and update the database.
Then everything should be work again.

Can you confirm me if that work?
I know about that issue but I thought I fixed that wit v4.3

Best
didiatworkz

**Comment by GhoperFX** [comment]
Hello 

I have the SOMO installation on a VM with Ubuntu Server and I suppose that the indications are for the path /usr/share/somo.

Inside that folder I have the version.txt with the value 4.1. I have tried to create the file you mentioned in the same path but it does nothing.

I do not know where to continue but if you tell me the DB issue could be related to the logs have a record referring to line 54 of the user.php file? 

We are in contact !, sure we will get it :-)

Greetings.

**Comment by didiatworkz** [comment]
Hello @GhoperFX ,
in the file: version.txt you need the string: `4.3` if you installed the version 4.3.
And then you need to execute this command: `echo 4.1 > /usr/share/somo/version_old.txt``
After that normally everything will work fine again,

Best
didiatworkz

**Comment by GhoperFX** [comment]
Hello.

I'm sorry but maybe I have explained myself wrong.

When I detected that the 4.1 version was showing me from one day to another the blank page I decided to upgrade to 4.3.

Seeing that the same thing was happening what I did was to revert the VM to version 4.1 to focus on the reason for this problem.

The truth is that at the moment if I can locate the problem on 4.1 I almost prefer it because I need nginx and in 4.3 it seems that it happens to use apache not ?.

The question is that seeing that in both versions the behavior is the same I guess it could be related to some information that is maintained between the two versions when the upgrade is done.

Is there a way to force some kind of "check" or something like that on the DB in version 4.1 ?

Greetings.

**Comment by GhoperFX** [comment]
I forgot another detail regarding version 4.1.

It may be that it does not work correctly with php version 7.4 ?

**Comment by GhoperFX** [comment]
Good news.

Although I still don't understand why ...

I have seen that from Firefox Developer Edition if I open correctly, both version 4.1 and 4.3 with DB migrated.

The strange thing is that the first thing I tried was to clear the cache of all browsers so I'm not clear if it could be something from Google Chrome and Safari ? (tested from 2 computers)

I will check it again calmly and report if I find something.

Thanks !

**Comment by didiatworkz** [comment]
Hello @GhoperFX,

oh sorry...

> Hello.
> 
> I'm sorry but maybe I have explained myself wrong.
> 
> When I detected that the 4.1 version was showing me from one day to another the blank page I decided to upgrade to 4.3.
> 
> Seeing that the same thing was happening what I did was to revert the VM to version 4.1 to focus on the reason for this problem.
> 
> The truth is that at the moment if I can locate the problem on 4.1 I almost prefer it because I need nginx and in 4.3 it seems that it happens to use apache not ?.
> 
> The question is that seeing that in both versions the behavior is the same I guess it could be related to some information that is maintained between the two versions when the upgrade is done.
> 
> Is there a way to force some kind of "check" or something like that on the DB in version 4.1 ?
> 
> Greetings.

Unfortunately, there is no option to check the integrity of the Database.
You can rename the database and import a copy of the dbase.sample.db and rename it back to the old one. 
If SOMO running again, it's a database problem.

SOMO work correctly with PHP7.4 - I don't recognize any issue here and yes, v4.3 work now with apache in the docker container. - Normally it's no problem to work with both since v4.3

The issue that you reported (Line 54 in user.php) occurs while the database not can find  or something is wrong with the admin user group in the database -> Maybe there is something wrong :/

Maybe a fresh installation will help, but I'm interested, what do you find out 😉 

Best
didiatworkz

**Comment by GhoperFX** [comment]
Hello.

We are still moving forward and it is still a mystery....

From another Windows 11 computer it is unable to load with Google Chrome and Mozilla Firefox, it only loads with Microsoft Edge :-/

Could it be some browser engine update that doesn't like some of the html code ?

**Comment by GhoperFX** [comment]
Hello.

I finally think I have located the problem.

Analyzing the loading of the index.php I found that the javascript at the end has a different behavior due to language issue.

If I comment it out and put it this way the page loads correctly:

<script>
	document.body.style.display = "block"
	flatpickr.localize(flatpickr.l10ns.default);
</script>

I hope I could have helped if it is a bug depending on the language.

Greetings.

**Comment by didiatworkz** [comment]
Hello @GhoperFX,

do you use the Spanish language?

Best
didiatworkz

**Comment by GhoperFX** [comment]
Yes

**Comment by didiatworkz** [comment]
Hey,

Then I found the issue in the translation file for es. 


When you want to quick fix that, you need to replace line 146 to `'flatpickr.lang' => 'es', `
in /assets/locale/es-ES.php   

I will fix that in general this weekend

Best
didiatworkz

**Comment by GhoperFX** [comment]
Hello !

Great, it is indeed fixed with that modification.

Congratulations on the project because it is a great job.

Merry Christmas ! ;-)

**Comment by didiatworkz** [comment]
Hello @GhoperFX 

Thank you very much for your feedback - I fixed it now!

I hope I'm saying it right:
Feliz Navidad

Best
didiatworkz

**Comment by GhoperFX** [comment]
Hello.

That's well said, Feliz Navidad ;-)

See you next time.

Greetings.
